title: Ignacio Brevis
#longtitle: long title test
logo: /assets/img/20230723_172413_small.png
description: <strong>Research Fellow</strong> at the University of Nottingham <br><a href="https://www.nottingham.ac.uk/mathematics/people/ignacio.brevis" target="blank">(University website)</a>
#email: ignacio.brevis at nottingham.ac.uk
show_downloads: False #True
theme: jekyll-theme-minimal
#remote_theme: sighingnow/jekyll-gitbook
