title: Ignacio Brevis
logo: /assets/img/20230723_172413_small.png
description: <p>Research Fellow at the University of Nottingham</p>
show_downloads: False #True
theme: jekyll-theme-minimal
#remote_theme: sighingnow/jekyll-gitbook
